### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by natanlao** [UCSC-CSE123/beavertail#21]
Running list of items to address in final report.

- [x] Security considerations
  * Minimizing collection of private data
  * Which components have access control?
  * What happens in the worst case scenario?
  * Security of having all data in-browser
  * Denial of service
  * Are there any features in the design not in the prototype?
- [ ] Test plan
  * How many buses do we expect a typical client to have?
  * How many of those buses can we reasonably simulate?
  * Results from testing?
  * Are there swappable components - e.g. wifi adapters?
- [ ] Licensing - what it is, why it matters
- [ ] Design for manufacturing and maintenance
  * Registration process? How do we configure new or replacement devices?
  * How can we make probes as easy to replace and repair as possible?
  * Our project is made of readily consumer available parts
- [x] Privacy considerations
- [ ] References
- [ ] Acknowledgements

**Comment by LexiKat** [comment]
Finished privacy considerations section. It's in section 2.2
