### ISSUE TITLE
Change management processes

### ISSUE THREAD

**Issue by natanlao** [UCSC-CSE123/beavertail#8]
We need to formalize our change management processes. This means:

- [x] Notion should be merged into Issues (if it's appropriate)
- [x] Minimum reviewers policy described and enforced
  * Our project primarily revolves around three domains
    - Sensor (Python): reviewers are KJ, Bryan, Natan
    - Server (Go): reviewers are Jorge, Natan, Alexis
    - Clieint (HTML/Javascript): reviewers are Jennie, Jorge, KJ, Natan
- [x] Formal CONTRIBUTING.md

**Comment by penguingovernor** [comment]
@kev231998 @bryan-kenneth can y'all take a look at [this](https://github.com/UCSC-CSE123/beavertail/blob/jorge-contributing/CONTRIBUTING.md) and add y'alls styling and guidelines ? 

Edit: Can @natanlao , @jennie-n , and @LexiKat  look at the Go guidelines above as well and see if y'all agree with it? (:

**Comment by natanlao** [comment]
> Use `go fmt` to format your code before committing.

This should be included in some test - setting up Travis for this would be overkill. I'll add this to the testing ticket.

Otherwise, I think it looks fine for our project.

**Comment by natanlao** [comment]
Maybe CODEOWNERS would be useful. I'm not sure if that's too much overhead.

**Comment by LexiKat** [comment]
Go Guidelines look good
